### ISSUE TITLE
Caching - We should support a time based cache as well as a size based cache

### ISSUE THREAD

**Issue by a-flammarion** [twigkit/frame#1]
Basically if the overall cache reaches a certain limit we start purging the old items on a FIFO basis.
Also. if a specific item has been in the cache for more than a configured amount of time and this item is requested again, we refresh the item.

@bjarkih What do you think?

**Comment by a-flammarion** [comment]
Using ehCache for this.
Will set the memory cache to 0 element. This will offload all elements to disk.

**Comment by a-flammarion** [comment]
Ok the problem is the ehCache expects the object that is cached to be serialisable. Which is obvious now... but the bufferedImage within the image object is not serialisable so I cannot actually cache it with ehCache.

What I can do is use ehCache to cache the fact that the file has been stored locally and whether it has expired or not.
But this means that unused files will not be cleared out of the cache...

**Comment by bjarkih** [comment]
What are we using for the cache at the moment?

**Comment by a-flammarion** [comment]
Nothing :-) Just a filepath where we store files.
We then check if the file exists when someone requests it, if it does we serve it from the filesystem if it doesn't we go fetch it from the url.

**Comment by bjarkih** [comment]
Got it :)

I would implement a cache (eh-cache) of the entries in our asset collection; i.e. the file paths. When an item gets evicted from the cache (we can listen for this in ehCache) we delete the corresponding file.

Makes sense?

**Comment by a-flammarion** [comment]
aha I see. Didn't know we could listen for it. I'll try this then.

**Comment by bjarkih** [comment]
Coolio - ping me if any questions!
